### ISSUE TITLE
Too many iterations error

### ISSUE THREAD

**Issue by ksw9** [xavierdidelot/TransPhylo#11]
Hi,
I'm coming across an error and was wondering how to suppress this so I can run long MCMC chains. My chain length is 10000. Thank you in advance!
Error in probTTree(ttree$ttree, off.r2, off.p, pi, w.shape, w.scale, ws.shape,  : 
  too many iterations, giving up!

**Comment by xavierdidelot** [comment]
Hi Katie,

This should be solved by the commit on Oct 22, 2018.
Could you please make sure that you are using the latest github version and report back?

Best wishes,
Xavier

**Comment by ksw9** [comment]
Dear Xavier,
Thank you for the quick response! I should've checked that sooner - yes, the newest release fixes the issue.
Best,
