### ISSUE TITLE
bactdating followed by transphylo

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/TransPhylo#12]
Hi,
It's me again, thanks for this lovely program. I've got a few questions, if you please 

1) I'm wondering if it is correct to use the output of BactDating as the input for TransPhylo, by using "write.tree(result$tree,'tree.nwk')", where "result" is the output of BactDating.

2) In the example, w.shape=10 and w.scale=0.1 were used, however in your paper, of the TB case,  w.shape=1.3 and w.scale=0.3 were used instead. Such two sets of parameters varies largely, so I'm wondering how I can determine the generation time parameter for my own dataset, a group of very closely related (pairwise SNP < 20) Klebsiella pneumoniae strains? which example should be used as the start point?

3) In an outbreak analysis, multiple isolates were sampled from the same patient at different time points, can I use them all in the transphylo analysis? or I should just leave one for each patient on the tree?

sorry for asking these questions and many thanks to you.

Yu

**Comment by xavierdidelot** [comment]
Hi Yu,

No worries, I'm very happy to answer questions about TransPhylo and/or BactDating.

1. yes this is fine.

2. indeed, these two parameters determine the generation distribution which depends on the pathogen you're studying. For Klebsiella a recent paper (van Dorp et al, MGen 2019) used w.shape=1 and w.scale=0.5 so you could use this at least as a starting point.

3. unfortunately at the moment TransPhylo is unable to use more than one isolate per patient.I would recommend selecting one isolate per patient at random.

Best wishes,
Xavier
