### ISSUE TITLE
Samples dated earlier than actual sampling date in t-tree

### ISSUE THREAD

**Issue by lborcard** [xavierdidelot/TransPhylo#20]
Dear All,

I am experiencing an issue with the transmission tree I generated. It appears to set the dates of certain samples (dated by sampling dates) earlier than the actual sampling date (e.g 2018 instead of 2021). The phylo tree was dated using bactdating and all samples are dated by sampling date. Is it normal behavior? 

best regards,

Loïc

**Comment by xavierdidelot** [comment]
TransPhylo does not change the sampling dates compared to what they are in the input phylogenetic tree.
Where do you see wrong sampling dates? Maybe you used
`plot(extractTTree(res))`
If so note that this plots the transmission tree with each case aligned with its infection time, not sampling time.

**Comment by xavierdidelot** [comment]
You need to specify the parameters of the generation time distribution, cf other previous issues on this such as #8 and #12. This needs to be specified in the same time unit as was used to created the dated phylogeny. See also a description of how to use TransPhylo at https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.60
