### ISSUE TITLE
summary.resTransPhylo

### ISSUE THREAD

**Issue by am-epi** [xavierdidelot/TransPhylo#25]
Hi, 

I'm wondering what the visual output/values for `summar.resTransPhylo` is supposed to be? Does it provide information about the avg number of hosts identified (unsampled and sampled) across the MCMC iterations and so on? I can get that for an individual iteration using `extractCTree` but would be good to have an overall summary if that makes sense.

I am also having trouble getting it working...
When I do just `summary(res)` I get the output `Result from TransPhylo analysis` and nothing else, when I do `print.phylo(phy)` by itself it gives me some info about the input tree. 
I have both transphylo and ape loaded but the function `summary.resTransphylo` isn't being recognised. 

Any help would be appreciated!
Thanks,
Abbi

**Comment by xavierdidelot** [comment]
Hi Abbi,

The function `summary.resTransPhylo` does not do anything indeed. 
You can use `print(res)` instead which gives the parameter estimates. 
To get the average numbers of sampled and unsampled individuals you can use the function `getIncidentCases(res)`

Best wishes,
Xavier

**Comment by am-epi** [comment]
Thanks for your help Xavier!
Best wishes,
Abbi
