### ISSUE TITLE
Temporal singnal detection

### ISSUE THREAD

**Issue by liuxiong714** [xavierdidelot/TransPhylo#31]
Thank you very much for your excellent tranmission analysis tool !

I have collected 23 isolates from a hospital infection outbreak and want to know the transmission relationship between the different patients.

A phylogenetic tree was build based on the recombination-free whole genome alignment using the iqtree software, and the BactDating was used to detect the temporal structure, however no temporal singal was deteced, the R suquare was very small (<0.1). 

My question is, based on this situation can I contiunue to use these 23 isolate genomes to build a tip-dated tree from Beast software and build a transmission tree using TransPhylo.

Thansk very much !

**Comment by xavierdidelot** [comment]
Hi Liu,

You can use either BEAST or BactDating to build the dated input tree needed by TransPhylo. However, if you found that the temporal signal is weak with BactDating, this is very likely to be the same with BEAST. One option may be to restrict the clock rate to a previously estimated value based on the literature of your pathogen of interest.

Best wishes,
Xavier
