### ISSUE TITLE
Save result as phylo object

### ISSUE THREAD

**Issue by MarliesJFrancine** [xavierdidelot/TransPhylo#33]
Hi,

After running the inferTTree() function, I would like to save the output transmission tree as a phylo object. Is this possible?
I have tried extractTTree() but this does not generate the transmission tree as a phylo object.

Kind regards,
Marlies

**Comment by xavierdidelot** [comment]
Hi Marlies,

The extractTTree() function returns the transmission tree, but this is in the form of a ttree object. A ttree object cannot be converted into a phylo object, because a transmission tree is not the same thing as a phylogenetic tree.

Best wishes,
Xavier
