### ISSUE TITLE
Multi-tree capability

### ISSUE THREAD

**Issue by MarliesJFrancine** [xavierdidelot/TransPhylo#34]
Hi, I read that TransPhylo can be used to infer transmission trees over multiple input trees
(here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7725332/). The article mentions analysis of multiple trees while using single parameters, but I am struggling to implement this in the following:
res<-inferTTree(ptree,mcmcIterations=1000,w.shape=w.shape,w.scale=w.scale,dateT=dateT)

Is there an example of this available somewhere? Or can you please provide some guidance?

For background information: I have ran a BEAST analysis and so I have multiple phylogenetic trees. Instead of selecting a single MCC tree I wish to capture as much of the signal as possible and use this "multi-tree capability".

Thank you in advance!

Kind regards,
Marlies

**Comment by xavierdidelot** [comment]
Hi Marlies,

The functionality that you mentioned is implemented in the command `infer_multittree_shar_param` and there is an example of how to use it here: https://xavierdidelot.github.io/TransPhylo/articles/multitree.html

Note however that this is NOT to be used on several tree sampled by BEAST in the way you described. Instead, the command `infer_multittree_shar_param` is designed to analyse several separate transmission clusters thought to share the same parameters. 

To do what you described, you would need to run the standard function `inferTTree` separately on several trees sampled by BEAST and compare/combine results.

Best wishes,
Xavier

**Comment by MarliesJFrancine** [comment]
Hi Xavier,

Great! Thank you for the clarification :)

Kind regards,
Marlies

**Comment by liamxg** [comment]
Dear @xavierdidelot ,

Could I know how to combine 10000 BEAST trees into TransPhylo, and  show the results, thanks.

Beast,

Liam

**Comment by xavierdidelot** [comment]
I think you're talking about 10000 trees sampled by BEAST from the same posterior distribution.
TransPhylo is designed to be run on a single consensus tree. 
If you want to run it on each sampled tree separately (eg to assess the effect of phylogenetic uncertainty) then you can run ob each one separately and compare the results.
