### ISSUE TITLE
Question about pi's function

### ISSUE THREAD

**Issue by PaulaSinis** [xavierdidelot/TransPhylo#35]
Dear Xavier, 

Thank you very much for the TransPhylo tool, I find it really useful. I am Paula Sinisterra, a PhD student. In our lab we are trying to apply TransPhylo to our genomic TB transmission clusters and I have one question. I recently read this in you paper from 2017: “It is often difficult in epidemiological studies to know the real function $\pi(t)$, but in situations where, for example, surveillance did not start before a certain date, the function  $\pi(t)$ we used here could be updated to reflect this”. This is exactly our case because in our dataset surveillance starts in the year 2014 while the dated phylogeny of individual clusters often date back to the year 2000. So my question is whether it would be very difficult in terms of code to update pi’s function to this situation and which characteristics should have the function. 

Thank you very much!
Paula.

**Comment by xavierdidelot** [comment]
Hi Paula,

This functionality exists in the TransPhyloMulti package, see https://github.com/DrJCarson/TransPhyloMulti 
So you might want to use this package, even if you only have a single genome per host.
See also the publication https://academic.oup.com/mbe/article/41/1/msad288/7505233

Best wishes,
Xavier

**Comment by PaulaSinis** [comment]
Thank you very much for the information!

Paula.
