### ISSUE TITLE
Printing Edges of the Transmission Tree

### ISSUE THREAD

**Issue by MarriaK** [xavierdidelot/TransPhylo#36]
Hi,

I am currently working with the TransPhylo model and I have successfully followed the instructions provided for inferring a transmission tree (https://xavierdidelot.github.io/TransPhylo/articles/infer.html). I was able to generate a transmission tree using the sample data provided.

However, I am now interested in accessing and printing the edges of the inferred transmission tree. Could you please guide me on how to achieve this? Any help or examples would be greatly appreciated.

**Comment by xavierdidelot** [comment]
As indicated towards the end of the tutorial, you can compute the medoid transmission tree using:
```
t=extractTTree(medTTree(res))
```
You can then plot this transmission tree in detailed format using `plotTTree(t,w.shape,w.scale)` or in economic format using `plotTTree2(t)`, cf help on these functions for some options of how to plot.

Or if you want the list of who infected whom in this transmission tree then you take a look at `t$ttree[,3]` which is a vector of infectors, with indexes corresponding to `t$nam`.

**Comment by liamxg** [comment]
Dear @xavierdidelot,

I've managed to extract the medoid transmission tree. To trace the specific transmission events, for example, to see whom individual 5 infected, which part of the output should I examine?

Thank you for your guidance.

ttree$ttree
           [,1]     [,2] [,3]
  [1,] 2023.954 2024.000    5
  [2,] 2023.909 2023.910    5
  [3,] 2023.953 2024.000    5
  [4,] 2023.926 2024.000    5
  [5,] 2018.273 2023.989  263
  [6,] 2023.988 2023.989    5
  [7,] 2023.987 2023.989    5
  [8,] 2023.986 2023.989    5


Best,
Liam

**Comment by xavierdidelot** [comment]
The third column tells you who is the infector of each case.
