### ISSUE TITLE
Gamma for acute and persistent

### ISSUE THREAD

**Issue by mwylerCH** [xavierdidelot/TransPhylo#37]
Dear Xavier,
many thanks for developing TransPhylo. I saw a couple of closed issues about the gamma distribution and the right shape and scale estimation, however I'm still unsure.
I'm working with a viral disease that displays a acute/transient form and a persistent/lifelong form. What do you think, can I still use TransPhylo for infection chains?
Many thanks in advance

**Comment by xavierdidelot** [comment]
Yes I think you could still use TransPhylo. The gamma distribution is quite flexible and has can have a long tail. That being said, if you want say 50% of the transmission to be in a matter of a few days and the other 50% to be in a matter of a years, then I don't think it will work. You would then need to make some changes to the code, for example using a mixture of two gamma distributions.

**Comment by liamxg** [comment]
Dear @xavierdidelot ,

how to set the gamma distributions for HIV datasets?

Best,
Liam

**Comment by xavierdidelot** [comment]
You could specify directly the mean and std of your generation time distribution using the `w.mean` and `w.std` arguments.
The unit needs to be the same as used in the dated tree. So for example if you tree is in years, and you consider that HIV has a generation time distribution with mean 10 years and standard deviation 5 years, you would use: `w.mean=10,w=std.5`

**Comment by liamxg** [comment]
Dear @xavierdidelot,

Thank you for this detailed clarification. I will configure the generation time distribution accordingly via the w.mean and w.std arguments.

To ensure I'm citing the methodology correctly, could you refer me to any specific literature that employs these parameter values for the HIV generation time distribution in a phylodynamic context?

Sincerely,
Liam

**Comment by xavierdidelot** [comment]
The values I mentioned were meant as just an example. You could search the literature for values that make sense in your context.
